services:
  wg-wish:
    image: ghcr.io/infastin/wg-wish
    environment:
      WG_HOST: ADDRESS OF YOUR SERVER (e.g. 23.192.228.84 or example.com)
      SSH_ADMIN_KEYS: >-
        YOUR AUTHORIZED KEYS GO HERE
    ports:
      - 51820:51820/udp
      - 51822:51822/tcp
    restart: unless-stopped
    volumes:
      - wg-wish-data:/var/lib/wg-wish
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
volumes:
  wg-wish-data:
